language: java

matrix:
  allow_failures:
    - os: linux # this is really about OSX, Ubuntu is just bonus
  include:
    - os: linux
      sudo: required
      language: android
    - os: osx
      osx_image: xcode9
      env: ANDROID_SDK_ROOT=/usr/local/share/android-sdk
      env: ANDROID_HOME=/usr/local/share/android-sdk

# The PPA is needed to provide all the fdroidserver deps on Ubuntu 14.04 trusty
addons:
  apt:
    sources:
      - sourceline: 'ppa:guardianproject/fdroidserver'
    packages:
    - bash
    - pylint
    - python3-dev
    - python3-libcloud
    - python3-pil
    - python3-pyasn1
    - python3-pip
    - python3-yaml
    - rsync
    - pep8
    - libjpeg-dev
    - zlib1g-dev
    - aapt
    - fdroidserver
    - npm

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null;
      brew install bash python3 libmagic;
      brew cask install android-sdk;
      mkdir "$ANDROID_HOME/licenses";
      echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license";
      echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license";
      echo y | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools";
      echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.2";
    else
      sudo pip3 install django;
    fi
  - ./setup.sh
  - sudo pip3 install -r requirements-dev.txt
  - npm install --user

script:
  - ./tests/test-units.sh

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - ls -lRa env
  - ls -lR | curl -F 'clbin=<-' https://clbin.com
